### PR TITLE
feat(ui): view Ithaca and Nostrocket horse in portfolio

### PR DESCRIPTION
**Pull request by angelicawill**
resolves https://github.com/holdex/marketing/issues/75

Test: https://holdex-venture-studio-git-75-humbleho-f5114f-holdex-accelerator.vercel.app/portfolio

## Summary by CodeRabbit

- **New Features**
	- Expanded the portfolio page with new project entries: "Ithaca Protocol" and "Nostrocket."
	- Added new tags for better categorization: 'nostr', 'social-dapp', and 'options-trading.'
	- Introduced conditional rendering for enhanced layout based on available data.
	- Updated the company logos section to include new entries: "HexTrust," "Ithaca," and "Nostrocket."

- **Bug Fixes**
	- Improved structure and consistency of the portfolio display.

### CODE REVIEW

**Comment by zolotokrylin** [comment]
see this comment please https://github.com/holdex/marketing/issues/75#issuecomment-2516233135

**Comment by zolotokrylin** [comment]
@angelicawill, anything is blocking you to finish it?

**Review by zolotokrylin — CHANGES_REQUESTED** [review]
https://github.com/holdex/holdex-venture-studio/pull/649#issuecomment-2516233821

**Comment by angelicawill** [comment]
> @angelicawill, anything is blocking you to finish it?

@zolotokrylin I didn't see your previous comment, my bad

**Comment by angelicawill** [comment]
@zolotokrylin where can I find the logo for humble horse?

**Comment by zolotokrylin** [comment]
@angelicawill use nostr rocket description, logo and link https://github.com/nostrocket. Use Nostrocket as a name, etc.

**Review by markholdex — APPROVED** [review]

**Pull request merged**
