### PR TITLE
fix(ui): space inconsistencies in learn section mobile

### PR DESCRIPTION
**Pull request by lmontero18**
ETA: 1 Hour

## Summary by CodeRabbit

- **New Features**
	- Introduced multiple reusable mixins for creating components, including `content-wrapper`, `header-wrapper`, `nav-crumbs`, `primary-button`, `button-icon-default`, and `guideCard`.
	- Added new sections to the template, enhancing layout with `main-section-standard`, `section-hero-wrapper`, and `section-kpis-wrapper`.
	- Expanded Tailwind CSS configuration with new spacing values for enhanced layout design.

- **Bug Fixes**
	- Adjusted class attributes in `section-learn-wrapper` mixin for improved styling consistency. 

- **Documentation**
	- Updated mixin signatures and descriptions for clarity.

### CODE REVIEW

**Comment by lmontero18** [comment]
@pr-time-tracker bug commit https://github.com/holdex/holdex-venture-studio/commit/c20cc8e && bug author @lmontero18

**Review by matthewvogas — CHANGES_REQUESTED** [review]
we dont have that padding in figma

Screenshot 2024-12-23 at 9 51 33 AM
Screenshot 2024-12-23 at 9 51 46 AM

**Comment by matthewvogas** [comment]
@lmontero18 pls update your eta

**Comment by lmontero18** [comment]
log; 30 minutes

**Comment by lmontero18** [comment]
log: 11:10 am UTC-6

**Comment by matthewvogas** [comment]
@lmontero18 pls update the ETA in the PR desc too, try to use realistic ETAs

**Review by matthewvogas — CHANGES_REQUESTED** [review]
@lmontero18 pls follow the pixel perfect figma guidelines
yours:
Screenshot 2024-12-23 at 11 10 52 AM
figma:
Screenshot 2024-12-23 at 11 11 12 AM

**Comment by lmontero18** [comment]
log: ETA 12:00 pm UTC-6

**Comment by matthewvogas** [comment]
@lmontero18 is this ready for review?

**Comment by lmontero18** [comment]
> @lmontero18 is this ready for review?

yes.

**Review by matthewvogas — APPROVED** [review]
looks nice

**Comment by matthewvogas** [comment]
@lmontero18 pls in your PR you need to add the issue linked. 'resolves: #--"

**Pull request merged**
