### PR TITLE
Fix parsing table cell lists in Google Conversion API

### LINKED ISSUE #309: Problem: Google Conversion API doesn't parse table cell lists
JSON Document - https://api.npoint.io/c8d0bf6bfd4cdb54328d

Scope:

- update `api/google-conversion` API request to parse the list elements inside table cell

### PR DESCRIPTION
**Pull request by accompany1205**
Fixes #309

### CODE REVIEW

**Comment by accompany1205** [comment]
@zolotokrylin , @georgeciubotaru Could you please review this PR?

**Comment by georgeciubotaru** [comment]
@Addis-Belete Please help with testing this functionality

1. Check for expected output via Postman request
2. Remove the `block` label  and leave a log regarding the availability of the task

**Comment by georgeciubotaru** [comment]
@Addis-Belete Also during `Squash and merge` please add these comments
image

```
Co-authored-by: George Ciubotaru <geeku96@gmail.com>
Co-authored-by: Addis Belete <addis.bel@gmail.com>
```

**Comment by Addis-Belete** [comment]
@accompany1205 
Can you create a branch on the original Holdex repo and merge your changes from this forked repo branch to it? So that I can easily pull your changes and test them locally.
Thanks

**Comment by georgeciubotaru** [comment]
@Addis-Belete There is no possibility of that. Try to connect to the PR via CLI

**Comment by accompany1205** [comment]
@georgeciubotaru , @Addis-Belete  do you like my PR?

**Comment by Addis-Belete** [comment]
> @georgeciubotaru , @Addis-Belete do you like my PR?

@accompany1205  On it

**Comment by accompany1205** [comment]
@Addis-Belete How is the result? I'm waiting for your feedback.

**Comment by Addis-Belete** [comment]
@georgeciubotaru Can you review this PR, please?

**Review by georgeciubotaru — APPROVED** [review]

**Comment by accompany1205** [comment]
@georgeciubotaru thanks for your review.
Could you confirm that my trial period has been passed successfully?

**Pull request merged**
