### PR TITLE
docs(ui): view cards on top of Guides page

### PR DESCRIPTION
**Pull request by angelicawill**
resolves https://github.com/holdex/marketing/issues/57

[Figma](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/Holdex?type=design&node-id=7017%3A51989&mode=design&t=t0tAdHirdZn2fo9l-1)

### CODE REVIEW

**Comment by angelicawill** [comment]
@zolotokrylin I made 2 versions in the Figma file, let me know your feedback.

**Review by zolotokrylin — COMMENTED** [review]
See my figma comments. Thanks.

**Comment by angelicawill** [comment]
checking

**Review by zolotokrylin — APPROVED** [review]

**Review by zolotokrylin — APPROVED** [review]
Good stuff 👍

**Pull request merged**
