### PR TITLE
fix: discord icon sizing

### LINKED ISSUE #458: Problem: The `Discord` icon sizing in the `Footer` is incorrect
Problem: The `Discord` icon sizing in the `Footer` is incorrect

_Originally posted by @predrag-us in https://github.com/holdex/holdex-venture-studio/issues/455#issuecomment-1635776643_

### PR DESCRIPTION
**Pull request by winter-sols**
fix #458

### CODE REVIEW

**Comment by winter-sols** [comment]
@georgeciubotaru , @markholdex, @predrag-us
Can you review this PR?

**Comment by predrag-us** [comment]
Preview required.

**Comment by winter-sols** [comment]
@georgeciubotaru could you re-deploy on Vercel?
I pushed new updates

**Comment by predrag-us** [comment]
Confirmed, all good.

**Review by georgeciubotaru — APPROVED** [review]

**Comment by georgeciubotaru** [comment]
@winter-sols Sync your branch with the `main` branch

**Comment by winter-sols** [comment]
@georgeciubotaru I'm sure this is ready to merge.

**Review by georgeciubotaru — APPROVED** [review]

**Pull request merged**
