### PR TITLE
fix(ui): adjust hero section spacing

### PR DESCRIPTION
**Pull request by lmontero18**
resolves: #651 

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `main-section-standard` for improved content organization.
	- Enhanced visual presentation of KPIs with updated background styles and padding.
	- Added `guideCard` components for educational content on Web3 security and decentralized finance.
	- Added a new `main-section` mixin for consistent section styling across the application.

- **Bug Fixes**
	- Minor adjustments to whitespace handling in the hero section.

- **Refactor**
	- Reorganized template structure for better responsiveness and visual consistency.

### CODE REVIEW

**Review by zolotokrylin — APPROVED** [review]

**Comment by zolotokrylin** [comment]
Merging this one because it fixes some major errors

**Comment by zolotokrylin** [comment]
@lmontero18 please reply to this comment: https://github.com/holdex/holdex-venture-studio/pull/652#issuecomment-2557894790

**Comment by lmontero18** [comment]
@pr-time-tracker bug commit [https://github.com/holdex/holdex-venture-studio/commit/300a20a3] && bug author @matthewvogas

**Comment by matthewvogas** [comment]
@lmontero18 you need to do it without [], so it will looks like this (with link)

Screenshot 2024-12-22 at 11 19 33 AM

**Comment by matthewvogas** [comment]
@lmontero18, are you sure that commit introduced the bug? cause in the preview of that commit looks nice 

https://holdex-venture-studio-git-feat-hero-s-587e0b-holdex-accelerator.vercel.app/#
Screenshot 2024-12-22 at 11 22 27 AM

**Comment by lmontero18** [comment]
@matthewvogas The issue stems from a conflict between two `main-section` mixins that exist in different files.

1. **Origin of the duplicated mixins**:
   - The original `main-section` comes from `common-mixins.pug`.
   - Your commit introduced a **new mixin also named `main-section`** in `index-mixins.pug`.

2. **The issue**:
   - When I had to use the `section-learn-wrapper` mixin (created in `index-mixins.pug` for a specific section), I imported `index-mixins.pug` into the `template.pug`.
   - This caused both mixin files (`common-mixins.pug` and `index-mixins.pug`) to be included, leading to an **override conflict between the two `main-section` mixins**.
   - As a result, the `hero-section` was using the wrong `main-section` mixin (the one without the `gap`), which caused the incorrect spacing in the `hero-section`.

3. **The fix I applied**:
   - I renamed the `main-section` mixin from `index-mixins.pug` to `main-section-standard` and updated the `hero-section` to explicitly use `main-section-standard`.
   - With this change, the `hero-section` now uses the correct mixin and the spacing issue is resolved.

This ensures there’s no mixin override, and each section can explicitly use the appropriate mixin without conflicts.

**Comment by matthewvogas** [comment]
> @matthewvogas The issue stems from a conflict between two `main-section` mixins that exist in different files.
> 
> 1. **Origin of the duplicated mixins**:
>    
>    * The original `main-section` comes from `common-mixins.pug`.
>    * Your commit introduced a **new mixin also named `main-section`** in `index-mixins.pug`.
> 2. **The issue**:
>    
>    * When I had to use the `section-learn-wrapper` mixin (created in `index-mixins.pug` for a specific section), I imported `index-mixins.pug` into the `template.pug`.
>    * This caused both mixin files (`common-mixins.pug` and `index-mixins.pug`) to be included, leading to an **override conflict between the two `main-section` mixins**.
>    * As a result, the `hero-section` was using the wrong `main-section` mixin (the one without the `gap`), which caused the incorrect spacing in the `hero-section`.
> 3. **The fix I applied**:
>    
>    * I renamed the `main-section` mixin from `index-mixins.pug` to `main-section-standard` and updated the `hero-section` to explicitly use `main-section-standard`.
>    * With this change, the `hero-section` now uses the correct mixin and the spacing issue is resolved.
> 
> This ensures there’s no mixin override, and each section can explicitly use the appropriate mixin without conflicts.

So the bug arises from the mix introduced in your PR?

**Comment by lmontero18** [comment]
Should the commit I reference be the one where the bug originated or the one where the bug became apparent and was pushed to the branch?

**Comment by matthewvogas** [comment]
@lmontero18 are you using etas? pls add the ETA in the description of the PR. cc @markholdex

**Comment by lmontero18** [comment]
> @lmontero18 are you using etas? pls add the ETA in the description of the PR. cc @markholdex

thanks for the observation, I'll add etas in my next pr's!

**Comment by zolotokrylin** [comment]
> Should the commit I reference be the one where the bug originated or the one where the bug became apparent and was pushed to the branch?

@lmontero18 You should reference the commit that has introduced the bug.

**Comment by lmontero18** [comment]
> > Should the commit I reference be the one where the bug originated or the one where the bug became apparent and was pushed to the branch?
> 
> @lmontero18 You should reference the commit that has introduced the bug.

Ok thanks!

**Pull request merged**
