### PR TITLE
fix: light theme fixes

### PR DESCRIPTION
**Pull request by MuhammadArslanKhan96**
As defined in issue #407 the light theme is partially implemented by design 

I found change in background colors of priceChart, optionGroup and tag
And there was no issue found in button and icon button

And I've fixed problem for optionGroup and tag only because chart was not being rendered so I was unable to fix the chart

### CODE REVIEW

**Comment by predrag-us** [comment]
Can you please release a preview? Thanks!
@georgeciubotaru @markcurchin

**Comment by predrag-us** [comment]
@MuhammadArslanKhan96 

OptionGroup ⏤ Please check the active background on light mode.
Tag ⏤ Please check the hover background on light mode.
Tag ⏤ Please check shadow when active on light mode. 

IconButton ⏤ Are you sure everything there's no issue? Doesn't look good in light mode. 

Implementation: 
CleanShot 2023-07-25 at 16 31 11@2x

Design:
CleanShot 2023-07-25 at 16 31 22@2x

**Comment by MuhammadArslanKhan96** [comment]
Icon buttons on design

Can you tell me which one will be on which state because how should I know which one will be used for which state? @predrag-us

**Comment by predrag-us** [comment]
@MuhammadArslanKhan96 

You can easily check which variant matches which state by selecting a variable and looking at the component props panel.

CleanShot 2023-07-26 at 09 06 02@2x

---

You did it right on `Tag` and `OptionGroup`. Good job! 👍

**Comment by MuhammadArslanKhan96** [comment]
Than you so much let me check them

**Comment by MuhammadArslanKhan96** [comment]
I've checked it and changed in the latest commit but it's not looking good I think but overall I've implemented it as in design thanks you @predrag-us

**Comment by predrag-us** [comment]
@MuhammadArslanKhan96 If it's implemented by design then it should look good.

---

Can you please update the preview? Thanks!
@georgeciubotaru

**Comment by MuhammadArslanKhan96** [comment]
@predrag-us you're correct but I think it's very dark

**Comment by MuhammadArslanKhan96** [comment]
According to design and implemention the background, border color and shadow was different so I just changed them and pushed it @predrag-us I got nothing else changed.

**Comment by predrag-us** [comment]
@MuhammadArslanKhan96 Let's see.
@georgeciubotaru When you can, please! 🙏

**Comment by MuhammadArslanKhan96** [comment]
@georgeciubotaru we can't open preview for all branches with out restriction except main and stage?

**Comment by predrag-us** [comment]
@MuhammadArslanKhan96 

I've totally missed the latest preview, sorry for the delay.

Unfortunately, your implementation is still not according to the design. 

What causes you a problem so you can't achieve proper implementation?

**Comment by markholdex** [comment]
There are no updates in the PR within the last 4 hours. The PR has been stale for more than 8 hours. Closing according to our Guideline Rules.

**Pull request closed without merging**
