### PR TITLE
feat: implement instant gist color theme switch on theme toggle

### PR DESCRIPTION
**Pull request by angelicawill**
resolves Holdex/marketing#17

Time spent: 30 minutes

### CODE REVIEW

**Comment by zolotokrylin** [comment]
Is this PR ready for review?

**Comment by angelicawill** [comment]
@zolotokrylin yes

**Comment by zolotokrylin** [comment]
@angelicawill then request review explicitly, please.

image

**Comment by zolotokrylin** [comment]
Good job! See my comment above @angelicawill

**Pull request merged**
