### PR TITLE
feat: embed github gist code snippets into articles

### PR DESCRIPTION
**Pull request by angelicawill**
resolves holdex/marketing#17

Time spent: 8 hours

### CODE REVIEW

**Comment by zolotokrylin** [comment]
Is this a draft or already ready for review?

**Comment by zolotokrylin** [comment]
@angelicawill if it is not ready for review, please keep it as DRAFT https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by zolotokrylin** [comment]
Something is off on mobile image

**Comment by angelicawill** [comment]
@zolotokrylin it seems like this issue is a problem of github gist.

try opening this in mobile:
https://codepen.io/lonekorean/full/WpvbOp

when loaded in mobile, the code won't align with the numbers. A workaround would be removing the numbers altogether. 

image

**Comment by zolotokrylin** [comment]
@angelicawill noted. 
I suggest we leave it as is, and fix it sometime later.

**Comment by angelicawill** [comment]
@zolotokrylin Then I'll mark this as ready for review. There's still a problem with the theme switcher function (the color scheme of gist only change after reload), but I'll create a separate PR for that.

**Comment by zolotokrylin** [comment]
@angelicawill what's the cost of fixing theme problem? If it is more than 1 hour max, it not worth it.

**Comment by angelicawill** [comment]
@zolotokrylin It will take more than 1 hour, since I still don't have any idea how to do it. The gist component is loaded through an iframe, which loads separately from the website. Hence it's tricky to insert custom css to the gist component, and add any prefer-color-scheme:dark css functions.

A quick solution is putting an invert(100%) css to the iframe component in dark mode, which visually creates a dark mode looking component, but it will be different from the Figma design. 
CleanShot 2023-12-10 at 17 17 44@2x

**Comment by zolotokrylin** [comment]
@angelicawill do the quick version. It is ok if it doesn't fit design for now 👍

**Pull request merged**
